const express = require('express')
const router  = express.Router()
const app = require('./index')
const {saywelcome,calculate,findGreatest,seniorCitizen,frameSentence,cgpaToPercent,learnStrict,learnLopp,learnDates,regExp,spreadRest} = require('./controller/basic')
const {createAdmin,updatePassword,updateManyPassword,insertManyAdmin,findReplace,deleteOne} = require('./controller/adminControl')
const {createUser,incrementBalance,findUser,filterUser,addAddress,compareDate,updateAddress,learnAggrigate} = require('./controller/userControl')
const{createLoan,findUserLoan}=require('./controller/loanControl')
const { route} = require('./index')

router.route('/').get(saywelcome)
router.route('/calculator').post(calculate)
router.route('/findGreatest').post(findGreatest)
router.route('/seniorCitizen').post(seniorCitizen)
router.route('/frameSentence').post(frameSentence)
router.route('/cgpaToPercent').post(cgpaToPercent)
router.route('/learnStrict').post(learnStrict)
router.route('/learnLoop').post(learnLopp)
router.route('/learnDates').get(learnDates)
router.route('/regExp').post(regExp)
router.route('/spreadRest').post(spreadRest)

router.route('/createAdmin').post(createAdmin)
router.route('/updatePassword').post(updatePassword)
router.route('/updateManyPassword').post(updateManyPassword)
router.route('/insertManyAdmin').post(insertManyAdmin)
router.route('/findReplace').post(findReplace)
router.route('/deleteOne').post(deleteOne)

router.route('/createUser').post(createUser)
router.route('/balanaceIncrement').post(incrementBalance)
router.route('/addAddress').post(addAddress)
router.route('/findUser').post(findUser)
router.route('/filterUser').get(filterUser)
router.route('/compareDate').post(compareDate)
router.route('/updateAddress').put(updateAddress)
router.route('/learnAggrigate').post(learnAggrigate)

router.route('/createLoan').post(createLoan)
router.route('/findUserLoan').post(findUserLoan)

module.exports = router